aggie-coding-club/Rev-Registration

autoscheduler/scraper/models/section.py
Closes #25.
This is generally what the meeting and section models should look like, but there are a couple things we should think about together:
- A lot of fields are IntegerFields (IDs, course & section numbers, etc.), but everything is stored in the data is a string. For some of these, I feel like storing them as IntegerFields will be beneficial (eg. sorting by course_num and section_num), but others (like IDs) are debatable.
- Delete behavior for section: Right now, on_delete is set to CASCADE for the section field in a Meeting, meaning if the section if belongs to is deleted, the meeting will as well. I feel like this is the correct behavior.
- ArrayFields: These seem like the easiest way to store meeting days, but can only be used with PostgreSQL. This shouldn't be a problem, but …
=> Created models for section and meeting

autoscheduler/scraper/models/instructor.py
Instructor's Meta class table property was `db_name`, but should have been `db_table`.
=> Fixed instructor table property

autoscheduler/frontend/src/App.tsx, autoscheduler/frontend/src/package-lock.json, autoscheduler/frontend/src/package.json, autoscheduler/frontend/src/theme.ts
Implements a global material ui theme, specifically setting the primary and secondary color for components. Also sets the HomeIcon to use the secondary color, just to demo that it's working.
Will squash into one commit on merge.
=> Implement global material-ui theme

autoscheduler/frontend/src/types/Course.ts, autoscheduler/frontend/src/types/Department.ts, autoscheduler/frontend/src/types/Instructor.ts, autoscheduler/frontend/src/types/Meeting.ts, autoscheduler/frontend/src/types/Section.ts
Currently, each of the classes we made for types call `Object.assign()` in the constructor to assign class members. However, when I was working on MeetingCard, I realized that this doesn't actually add it to the properties typescript gives to its class. Declaring all members up-front fixes this.
=> Fixed types to correctly declare class members

.github/workflows/backend-workflow.yml, .github/workflows/frontend-workflow.yml
There's really no need for the frontend steps to be checked on the backend branches and vice-versa. As such, this splits up the action into separate parts, which will only be run on their respective branches on push. 
This way, we won't have failing jobs on  branches that are caused by problems in the backend, such as the Django files failing pylint.
Also, I won't be merging these changes into `frontend/master` and `backend/master` until I also make a PR for Danger, which I'll make after this gets merged.
=> Split actions workflow into separate front/backend parts

autoscheduler/frontend/src/components/LandingPage/HelpText.tsx, autoscheduler/frontend/src/components/LandingPage/SelectTerm.tsx, autoscheduler/frontend/src/components/NavBar.tsx, autoscheduler/frontend/src/tests/SelectTerm.test.tsx
I've fixed various mistakes in the landing page:
- eliminated an error due to Material-UI only accepting 'top' as the anchorOrigin.vertical prop
- eliminated an error due to having `Typography` inside of `Box`
- menu icon is now showing
- `useStyle` now refers to the app theme, as it is supposed to
I would like @f4alt to review these changes for understanding before merging them into the main feature branch for `frontend-welcomepage`
=> Landing Page Fixes

docker-entrypoint.sh
Running docker with GitHub actions doesn't clear the database, meaning that if some migrations are already applied, our backend CI can fail because the table is incorrect. This fixes the problem by first running `makemigrations --empty scraper`, meaning migrations are now created from scratch as they should.
Check out [this pull request on my fork](https://github.com/ryan-conn/Automatic-Aggie-Scheduler/pull/1) for verification that the fix works, it uses Carlos' course scraping branch as a base (where our CI failed) and applies this change over it
=> Reset migrations before creating them

autoscheduler/frontend/src/components/Schedule/Schedule.css
Fixes the transparent background of the schedule component. The only problem I will note is that the time bars now look bad on Google Chrome but fine on Firefox for some reason.
Google Chrome:
Firefox:
Closes #117
=> Fix schedule background

autoscheduler/scraper/serializers.py, autoscheduler/scraper/tests/api_tests.py
Fixed the expected formatting in section API tests, and changed `SectionSerializer` to format time objects correctly. I'd like @btgathright to review these changes and make sure everything is okay
=> Section API Fixes

autoscheduler/frontend/src/.eslintrc.js, autoscheduler/frontend/src/redux/actionTypes.ts, autoscheduler/frontend/src/redux/actions.ts, autoscheduler/frontend/src/redux/reducers.ts, autoscheduler/frontend/src/tests/Redux.test.ts, autoscheduler/frontend/src/tests/ReduxAvailability.test.tsx, autoscheduler/frontend/src/types/Availability.ts, autoscheduler/frontend/src/types/DayOfWeek.ts
"Squashed" all of the Redux updates for availability input into one separate PR. Now that I think about it, I think one of the benefits of Redux is supposed to be isolation of logic from UI, which I guess is coming in handy now.
"Squash" is in quotes because I actually just used `git checkout frontend/availability redux/`, which has effectively the same result.
=> Redux updates to handle availability

autoscheduler/scraper/tests/api_tests.py
Since the current tests for `/api/course/search` aren't all that thorough, I added tests to make sure that lowercase letters in searches, as well as numbers and spaces (encoded as `%20`), are correctly handled.
=> Additional testing for /api/course/search

autoscheduler/scraper/models/course.py, autoscheduler/scraper/serializers.py, autoscheduler/scraper/tests/api_tests.py, autoscheduler/scraper/urls.py, autoscheduler/scraper/views.py
Implements api/terms and api/course/search. For api/course/search, white space between the department and course number is trimmed. Department must also be entered before course number in the search parameter.
=> Scraper API Term & Course Search

autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicSelect.tsx, autoscheduler/frontend/src/tests/CourseSelectColumn.test.tsx
Due to an error I made when connecting `<BasicSelect />` to Redux, there was a bug in that clicking on "Web Only" or "Honors Only" on any course card other than the first would cause the box to not actually be checked, along with an error message about an uncontrolled component becoming controlled. Since this was my fault originally, I have resolved this bug by assuming that all checkboxes should be false in the initial state, and I now propose that this branch be merged into the main `frontend/course-picker` branch.
=> Fixed bug when clicking on second course card

autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectColumn.css, autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectColumn.tsx, autoscheduler/frontend/src/tests/CourseSelectColumn.test.tsx
I made the course cards in the course select column change their padding based on whether there is a scroll bar in the component or not, instead of always keeping 2% padding. Here's what it looks like:
I'm not sure if the way I select elements is the best way to do so (`getElementById` and `getElementsByClassName`). As far as I can tell, we would have to change this to a class component to use refs in order to modify CSS after rendering, but if there's a better way to do so I'd like to know.
=> Made course card padding depend on if there's a scrollbar or not

autoscheduler/scraper/management/commands/scrape_courses.py, autoscheduler/scraper/tests/commands/scrape_courses_tests.py, autoscheduler/scraper/tests/data/section_input.json
Making the scheduling algorithm, I realized that we don't actually scrape whether sections are web or online (which I need to test section filtering), so I added that functionality. I also made slight improvements to `parse_course` (see my commit messages) fixed a bug with honors section titles (which start with `HNR-`) being parsed directly, and added tests for these new functionalities.
=> Improvements to course scraping

autoscheduler/frontend/src/components/LandingPage/SelectTerm/SelectTerm.tsx, autoscheduler/frontend/src/redux/actions/term.ts, autoscheduler/frontend/src/redux/reducer.ts, autoscheduler/frontend/src/redux/reducers/term.ts, autoscheduler/frontend/src/tests/SelectTerm.test.tsx, autoscheduler/frontend/src/tests/redux/Term.test.ts
Makes it so that when you select the term on the landing page, it brings you to `/scheduling`, and sets the current term in the Redux store so it can be accessed when we fetch to the backend.
Closes #146
=> Connects landing page to main page

autoscheduler/autoscheduler/urls.py, autoscheduler/scheduler/create_schedules.py, autoscheduler/scheduler/tests/api_tests.py, autoscheduler/scheduler/urls.py, autoscheduler/scheduler/utils.py, autoscheduler/scheduler/views.py, autoscheduler/scraper/serializers.py, autoscheduler/scraper/tests/api_tests.py
Implements the scheduling api at /scheduler/generate.
We can't include the `api` in the route since it redirects to scraper.urls, but we can modify it if we want to.
Closes #165
=> Implemented scheduling api route

.github/workflows/deploy-workflow.yml
Meant to do this in the GCP deploy PR but I got a bit to eager and merged it before hand
=> Made deploy workflow only run on pushes to master

.github/dangerfile.ts, .github/workflows/backend-workflow.yml, .github/workflows/frontend-workflow.yml
- Makes the frontend & backend steps run on all pushes/not ignore `backend/` and `frontend/` branches respectively.
- Removed the check in danger that gave an warning when you touch frontend related files on `backend/*` branches and vice-versa
=> Misc Actions/CI changes

.github/workflows/deploy-workflow.yml, .gitignore, autoscheduler/autoscheduler/settings/base.py
This mainly adds the `SETTINGS_MODE=proxy` option, as the `STATIC_URL` has to be pointing to the actual static files rather than cloud storage. Likewise the only thing that `prod` is actually used for is collecting static files, so I changed that settings mode to `static` instead.
Also `cloud_sql_proxy` to the `.gitignore`
=> Django settings fix for Cloud SQL proxy

autoscheduler/scraper/views.py
Pretty simple PR, currently our search results look like this:
```json
{
"results": [
"ACCT 621",
"ACCT 210",
"AERO 212",
"ACCT 622",
"ACCT 624",
"ACCT 640",
"ACCT 230",
"AERO 214",
"ACCT 327",
"AERO 401",
"ACCT 648",
"AERO 222",
"ACCT 650",
"ACCT 328",
"ACCT 665",
"ACCT 329",
"ACCT 408",
"ACCT 427",
"ACCT 447",
"AERO 402",
"ACCT 450",
```
They're not being sorted, so it just returns them in the order they are in the table. By sorting, the results look like this:
```json
{
"results": [
"ACCT 209",
"ACCT 210",
"ACCT 229",
"ACCT 230",
"ACCT 327",
"ACCT 328",
"ACCT 329",
"ACCT 403",
"ACCT 405",
"ACCT 407",
"ACCT 408",
"ACCT 410",
"ACCT 421",
"ACCT 427",
"ACCT 447",
"ACCT 450",
"ACCT 484",
"ACCT 491",
"ACCT 603",
"ACCT 607",
"ACCT 610",
"ACCT 611",
"ACCT 612",
"ACCT 621",
"ACCT 622",
"ACCT …
```
=> Sort api/course/search results by dept and course_num

autoscheduler/scraper/management/commands/scrape_grades.py
Adel's recently merged #188 PR (9b4ca31) failed linting even though it wasn't before for some reason, so this fixes that. 
I have no idea why this isn't giving a linting error in #224 but w/e
=> Removed unnecessary f-string from scrape_grades

.pylintrc, autoscheduler/scraper/management/commands/scrape_courses.py, autoscheduler/scraper/management/commands/scrape_grades.py, autoscheduler/scraper/management/commands/utils/scraper_utils.py
Since using `bulk_create` directly on our data isn't possible in Cloud SQL given how many objects we scrape (240k sections, 320k meetings, 80k courses, 98k grades), I made a function to split our lists into slices, and pass these slices into `scrape_courses` and `scrape_grades`. I decided not to change how `scrape_depts` works since there less than 6000 departments across all terms, but we can easily change this if we want. I tested that this works by running `scrape_depts` then `scrape_courses` and `scrape_grades` and saving the models to a new database in GCP, then checking that the correct number of records exist in the database for each model.
If you're curious, here are the runtimes of `scrape_courses` on GCP with slices of 10,000 objects:
And with slices of size 50,000:
Closes #212.
=> Made scraping bulk_create in slices

autoscheduler/scraper/management/commands/scrape_grades.py
Since scrape_grades previously took 15-20 minutes to run, I modified it to use multiple processes so that the PDF retrieving & parsing actually runs in parallel. 
Be aware that if you run it without using a `-p` argument with less than the number of cores you have, your computer will be slow af since it's probably at 100% CPU usage.
These were my runtimes scraping all of the grades on an i5-9600k @ 3.7 Ghz (overclocks to ~4.2 GHz) w/ 6 cores. Command ran was `python manage.py scrape_grades -p N`, where N = __# of processes__
| # of processes | Time taken | Speedup (Time for 1 proc / Time for n proc) | Efficiency (speed up / # proc) |
| -------------|-------------|-------|-----|
| 1 | 15.05 min | 1 | 1 |
| 2 | 8.11 min | 1.85 | 0.92 |
| 4 | 4.30 min |  3.5 | 0.87 |
| __6__ | 3.25 min | …
=> Changed scrape_grades to use multiprocessing

autoscheduler/frontend/src/components/LandingPage/SelectTerm/SelectTerm.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.tsx, autoscheduler/frontend/src/package-lock.json, autoscheduler/frontend/src/package.json, autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/redux/actions/term.ts, autoscheduler/frontend/src/redux/reducers/term.ts, autoscheduler/frontend/src/tests/redux/Redux.test.ts, autoscheduler/frontend/src/tests/redux/Term.test.ts, autoscheduler/frontend/src/tests/ui/App.test.tsx, autoscheduler/frontend/src/tests/ui/CourseSelectCard.test.tsx, autoscheduler/frontend/src/tests/ui/SchedulingPage.test.tsx, autoscheduler/frontend/src/tests/ui/SelectTerm.test.tsx, autoscheduler/frontend/src/tsconfig.json, autoscheduler/scraper/tests/api_tests.py, autoscheduler/scraper/views.py
Connects the `SelectTerm` component to /api/terms, as well as a couple other changes in order to make the data between our frontend/backend more consistent:
- `term` in the redux store is now a string, as that's what it's stored as on the backend. (If we'd rather change it on the backend to a number instead, I can do that)
- `/api/terms` now returns results in the order `description -> term code`, since descriptions map to their corresponding term codes, not the other way around
I also updated `tsconfig.json` to use es2018, as it makes translating objects into maps easier with the `Object.entries(obj)` function. Since our website already doesn't work with internet explorer, this shouldn't really be a problem, but we should consider using a polyfill library to hopefully make it compatible. …
=> Connected /api/terms to SelectTerm

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicSelect.tsx, autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/tests/redux/CourseCardRedux.test.ts, autoscheduler/frontend/src/types/CourseCardOptions.ts
Optimizes the way that `SectionSelected` objects are created by parsing them directly from the section data we get from the API. I also added `hasHonors` and `hasWeb` as parts of the course card state, so that they only have to be calculated when sections are parsed again.
I realized that it's far more effort than it's worth to remove the `SectionSelected` class (as it would create a circular dependency between `Section` and `Meeting` and even if I make `Meeting` just take section nums/ids instead of a section object, it would involve a huge amount of refactoring), so I didn't change it at all.
Closes #241.
=> Refactored parseMeetings to parseSections

autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/redux/testData.ts, autoscheduler/frontend/src/tests/redux/CourseCardRedux.test.ts, autoscheduler/frontend/src/tests/redux/Redux.test.ts, autoscheduler/frontend/src/tests/redux/Schedule.test.tsx, autoscheduler/frontend/src/tests/testSchedules.ts, autoscheduler/frontend/src/tests/types/Grades.test.ts, autoscheduler/frontend/src/tests/types/Meeting.test.ts, autoscheduler/frontend/src/tests/ui/MeetingCard.test.tsx, autoscheduler/frontend/src/tests/ui/Schedule.test.tsx, autoscheduler/frontend/src/types/Grades.ts, autoscheduler/frontend/src/types/Section.ts, autoscheduler/scraper/serializers.py, autoscheduler/scraper/tests/api_tests.py
I added the grades field to the Section type, as we'll need it for the schedule GPA calculating in #193 (and I didn't want to do it in that PR), as well as for the grade distributions (#163).
I also made the `SectionSerializer` return `None` instead of `Grades` models where all of the fields were null in the cases that a prof has no previous grades out for a course, as it makes it much easier to handle on the frontend.
=> Added grades to Section type

autoscheduler/frontend/src/tests/redux/CourseCardRedux.test.ts
Since I didn't rebase with master for #232 before merging, it ended up failing the tests as I added `parseMeetings` tests in it, but Ryan changed it to `parseSection` and I didn't reflect those changes in my branch.
=> Corrected CourseCardRedux tests

autoscheduler/scraper/management/commands/scrape_courses.py, autoscheduler/scraper/tests/commands/scrape_courses_tests.py
Small bug, but `parse_instructor` would return `None` anytime an instructor was already visited, which resulted in lot of sections having `None` instructors when they shouldn't (i.e. for `201531`). This fixes that bug and adds a test for it.
=> Parse instructor fix

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx, autoscheduler/frontend/src/tests/ui/CourseSelectCard.test.tsx
This adds the showing of ONLINE for meeting times that are `00:00`. I used the assumption that if the startTime for a meeting is 0, then it's safe to assume that the rest of them are also 0, meaning that it's an online meeting time.
Closes #184
=> Show ONLINE for online meetings in SectionSelect

autoscheduler/frontend/src/components/SchedulingPage/Schedule/ScheduleCard/ScheduleCard.css
Before:
After:
I don't know if this is something that Jest can test, since it pretty much requires looking at the screen. I also wasn't sure if JSDom would mock Z-indices, but I could try comparing those if y'all think it would be worth it.
Closes #219
=> Meeting times are no longer covered up by adjacent meetings

autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.tsx, autoscheduler/frontend/src/package-lock.json, autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/tests/redux/CourseCardRedux.test.ts, autoscheduler/frontend/src/tests/testData.ts, autoscheduler/frontend/src/tests/ui/ConfigureCard.test.tsx, autoscheduler/frontend/src/tests/ui/SchedulingPage.test.tsx, autoscheduler/frontend/src/timeUtil.ts, autoscheduler/scheduler/views.py
Connects the `Generate schedules` button to /scheduler/generate.
Currently I handle the BASIC/SECTIONS customization level by if the SECTIONS option is selected, then the options for the honors/web only are set to the default. And if the BASIC option is selected, then the sections aren't sent. We might want to modify this for sessions so we *always* have the data in order to save it, and we can instead just send the current customization level for each section, and `create_schedules` can then choose which one it wants to ignore. Should be a relatively easy fix.
Also think we might want to add some tests for this that I missed, as the availabilities time converting was messed up and I didn't catch it for awhile, so lmk if you have any ideas for tests to add.
I also had to change the course …
=> Connected generate schedules

autoscheduler/scraper/tests/api_tests.py, autoscheduler/scraper/views.py
Terms are now shown in the order College Station, Galveston, Qatar rather than reversed
Look at the home page, all terms are now in the order that we wanted
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/28655462/84597707-705a1500-ae2b-11ea-8355-828f87793e4b.png)|![image](https://user-images.githubusercontent.com/28655462/84597697-5b7d8180-ae2b-11ea-8986-2c5f06360f0b.png)|
Closes #245.
=> Made api/terms show College Station terms first

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx, autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/tests/ui/ConfigureCard.test.tsx, autoscheduler/frontend/src/tests/ui/CourseSelectCard.test.tsx
Added an icon for honors sections and appropriate tests. Currently, the icon is gray to match th professor's name, and there isn't a whole lot of space between the text and the icon. Seems fine to me, but if y'all don't like it, it's an easy fix.
Closes #230
=> Added icon to honors sections

autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.tsx, autoscheduler/frontend/src/tests/ui/ConfigureCard.test.tsx
The `<ConfigureCard />` had been sending raw `SectionSelected` objects instead of a list of section numbers, so this PR fixes that issue with a quick `.map()`
The testing was more complicated than the 2 lines of actual code changes
Pick a course, select 2 sections, then see that there are only 2 schedules generated. Also added a test in `ConfigureCard.test.tsx` to prevent this in the future.
N/A
Closes #283
=> Fix filtering by section

autoscheduler/autoscheduler/settings/base.py, autoscheduler/autoscheduler/urls.py, autoscheduler/frontend/src/components/LandingPage/SelectTerm/SelectTerm.tsx, autoscheduler/frontend/src/components/SchedulingPage/SchedulingPage.tsx, autoscheduler/frontend/src/tests/ui/SchedulingPage.test.tsx, autoscheduler/frontend/src/tests/ui/SelectTerm.test.tsx, autoscheduler/user_sessions/tests/api_tests.py, autoscheduler/user_sessions/tests/term_api_tests.py, autoscheduler/user_sessions/urls.py, autoscheduler/user_sessions/views.py
Sessions now store the last term code used, so when you refresh on the schedule page, it will automatically set your term.
I can't think of anything controversial in this PR, the website should work as it did before without cookies (and therefore sessions) enabled
Select a term on the landing page, then refresh the page and notice that search results correspond to the term you selected
Adds part of the functionality of #260, storing all of the data for a term will likely be pretty complicated (it'll at least involve adding redux actions to overwrite each slice of state and adding additional API routes), so that will be done in a separate PR, since the two are only related in that they both involve the use of sessions.
=> Store term in sessions

autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.tsx, autoscheduler/frontend/src/tests/ui/ConfigureCard.test.tsx
I often hit "Generate Schedules" and then sit for a very confusing minute wondering why it's taking so long, until I realize that I didn't check "Include full sections". Users will almost certainly make similar mistakes, so we need an error handling method to let them know that they need to change their filters. To this end, I have added a snackbar that shows when the Generate Schedules  button returns no schedules.
***tests coming soon***
I think the only possible controversial thing here would be the text in the error bar. It currently reads "No schedules found. Try widening your criteria." Let me know if you'd like something else.
Hitting Generate Schedules without adding any courses is the easiest way to test this.
Closes #278
=> Shows snackbar when no schedules can be generated

autoscheduler/frontend/src/components/SchedulingPage/Schedule/Schedule.tsx, autoscheduler/frontend/src/components/SchedulingPage/Schedule/meetingColors.ts, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ColorBox.tsx, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/MiniSchedule.tsx, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/MiniSchedule/MiniSchedule.css, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/MiniSchedule/MiniSchedule.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/MiniSchedule/MiniSchedule.tsx, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.css, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.tsx, autoscheduler/frontend/src/tests/ui/Schedule.test.tsx
Added a mini-schedule to the schedule preview component to summarize generated schedules. Couple of design decisions I made: I didn't like how rounded borders looked, so I used rectangles. I also currently have a minimum height but no maximum height. It might be better to standardize the heights for all of them, regardless of how big the `<ListItem />` is. Also, let me know if the spacing feels off.
Closes #183
=> Added mini schedule to schedule preview

.github/workflows/deploy-workflow.yml, autoscheduler/autoscheduler/settings/base.py
In re-creating the GCP setup, the DB connection name & storage URL were changed, so this updates them. Frankly these should probably shouldn't be tracked / we should pass them in as secrets, but I don't want to change it (and it would be annoying for like using the proxy for updating the DB) so I'm leaving it alone for now.
I made the deploy workflow work on pushes temporarily to test this, so visit http://revregistration1.appspot.com to check! 
Closes #250
=> Update GCP Database & Storage names

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.tsx
So I fixed the annoying warning we got with the `CourseSelectCard` tests about no option being selected. Basically , I told it to select the first option. In the browser, however, this only works after you type at least two letters, which is good enough for me.
¯\\\_(ツ)\_/¯
It's like a one-line change, just read the code.
I did also add some underscores for unused arguments on the functions below it, just for better linting
Run `npm run test`. You hsould get no yellow warnings. There are still some red warnings about an update not wrapped inside `act`, but I believe I fixed those in #278 
N/A
I acutally don't think we ever made one for this
=> Got rid of getOptionSelected warning in tests

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/GradeDist/GradeDist.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/GradeDist/GradeDist.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/GradeDist/GradeDist.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx, autoscheduler/frontend/src/tests/redux/CourseCardRedux.test.ts, autoscheduler/frontend/src/tests/types/Grades.test.ts, autoscheduler/frontend/src/tests/ui/GradeDist.test.tsx, autoscheduler/frontend/src/tests/ui/SchedulePreview.test.tsx, autoscheduler/frontend/src/types/Grades.ts, autoscheduler/scraper/models/grades.py, autoscheduler/scraper/serializers.py, autoscheduler/scraper/tests/api_tests.py, autoscheduler/scraper/tests/models_tests.py
This adds grade distribution displaying to the `SectionSelect` for each instructor group. It also adds the counting of the total amount of sections to `GradesManager.instructor_performance`, so we can display the `From X total sections` text when the GPA is hovered over (thanks for the idea www.aggiegrades.com)
Not sure if there are any edge cases that I can think of. I've just been testing it with `CSCE 121- 202031`, which is my go to typically. 
|1080p|1440p|
|--|--|
|![chrome_PU3RrvU9Zu](https://user-images.githubusercontent.com/7295783/83978593-499d5b00-a8ce-11ea-8c68-e0582d5ba21e.png)|![chrome_ZRthy0cd3G](https://user-images.githubusercontent.com/7295783/83978596-4bffb500-a8ce-11ea-9872-30b89ad413b4.png)|
Closes #163
=> Added grade distribution displaying to SectionSelect

autoscheduler/scraper/management/commands/scrape_courses.py, autoscheduler/scraper/management/commands/scrape_grades.py, autoscheduler/scraper/management/commands/utils/scraper_utils.py
Previously `scrape_courses` wouldn't override the previous data in the database since `bulk_create` doesn't overwrite on conflicts. 
This makes it overwrite previous entries by deleting them & uploading them. Hopefully adding the `transaction.atomic()` makes all of these commit at once, so there isn't a window where the models won't exist.
I deleted `slice_every` since it's really not necessary, as `batch_size` for `bulk_create` provides the same functionality. Sorry Ryan 😢 
Run `scrape_courses` for a given term and check if it updates it. A quick way to check if it updates it (assuming the last time you ran it was before the Fall 2020 courses were updated) is to run the server & check (for `202031`) if `CSCE 121 - 200` exists. Before the fall semester shift it existed, but afterwards it …
=> Made scrape_courses override previous data

autoscheduler/scraper/tests/aio_test_case.py
There must've been some pylint update or something, but the `aio_test_case` file randomly started failing linting, so this fixes it
=> Fixed aio_test_case linting error

autoscheduler/frontend/src/components/NavBar.tsx, autoscheduler/frontend/src/tests/ui/App.test.tsx, autoscheduler/user_sessions/tests/name_api_tests.py, autoscheduler/user_sessions/tests/term_api_tests.py, autoscheduler/user_sessions/urls.py, autoscheduler/user_sessions/views.py
This pull request creates an API that allows for the logged in User's name to be retrieved. It is used to replace the login text where the login option used to let the user know their log in was successful. Should not be merged until after Social Auth.
Honestly kinda hard to do at the moment because it's not done and the name showing is kinda implemented poorly as it overwrites the login button text and ideally it would replace the button with a logout button or something that displayed the name but that would require a logout API (or clearing cookies) I think and that might be a separate PR.
Despite the fact this shouldn't be merged until after Social Auth, I kinda needed code from that branch in order to get this one to work so I added that code to this branch. If you just boot up the …
=> User sessions/get first and last name api

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.tsx
`CourseSelectCard` used to show all options as selected, this quick PR patches that so that only the first option is selected by default
No test included because the functionality is mostly related to an external library (Material UI)
Start typing in the `CourseSelectCard`. Only the first suggestion should be highlighted in gray.
|Before|After|
|--|--|
|![before](https://user-images.githubusercontent.com/10082177/91732924-88118180-eb6e-11ea-864a-698f47df0602.jpg)|![after](https://user-images.githubusercontent.com/10082177/91732946-8e9ff900-eb6e-11ea-8918-699c98f8082a.jpg)|
=> No longer selects all options

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.tsx
Used to be that if you selected the same course twice, the name would disappear. This was because I had a function that would clear the autocomplete if the input value didn't match any of the courses. since `CSCE 121` isn't going to exactly match `CSCE 121 - INTRO PRGM DESIGN CONCEPT`, I decided that a better way to do this would be to check if the `options` array returned by the backend was empty. That way, all filtering occurs at the backend level and the frontend just displays the results rather than applying any additional filtering.
I have no idea how to set up the mocks to test this bug. If anyone has any ideas, I'd be willing to try them out, but for now, I've just patched the bug.
- Enter a course and select it so that it fetches sections for the course
- Instead of clicking the …
=> Fix bug with course name disappearing

autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.tsx
Fixes the error `415 Unsupported media type "text/plain;charset=UTF-8" in request.` by adding a `Content-Type` header to `scheduler/generate`
DRF expects the `Content-Type` to be set (see [this page](https://www.django-rest-framework.org/api-guide/parsers/#how-the-parser-is-determined)), and since we weren't setting it, there was no guarantee that requests would be handled properly.
Click the generate schedules button, and now instead of a 415 error, you get a 403 error (which we need to fix separately for all of our POST + PUT requests)! Hooray! Our tests were already setting `Content-Type`:
```python
result = self.client.post('/scheduler/generate', request_body, format='json')
```
so there's no need to change anything there.
We don't have an issue for this problem, but Gannon pointed it …
=> Fix 415 error in scheduler/generate

.github/workflows/deploy-workflow.yml, autoscheduler/.gcloudignore, fill_google_auth_credentials.sh
Pretty straightforward - this adds the filling of the `.env` file for Google Auth.
Per 6c7d749, I added a temp commit that makes the deployment run on PR so we can double check that this is actually working. As such, just go to http://revregistration.com and check that you can log in with Google!
Note that frankly this is a terrible way of testing this (cause I could break the deployment), but lol yolo
Closes #314
=> Add Google Auth .env filling for CD

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.tsx, autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/redux/reducers/courseCards.ts, autoscheduler/frontend/src/tests/redux/CourseCards.test.ts, autoscheduler/frontend/src/tests/redux/Redux.test.ts, autoscheduler/frontend/src/tests/ui/ConfigureCard.test.tsx, autoscheduler/frontend/src/tests/ui/CourseSelectCard.test.tsx, autoscheduler/frontend/src/tests/ui/CourseSelectColumn.test.tsx, autoscheduler/frontend/src/types/CourseCardOptions.ts, autoscheduler/frontend/src/utils/createThrottleFunction.ts, autoscheduler/frontend/src/utils/throttle.ts
This PR moves `loading` for course cards into redux, and makes a couple of really nice changes that are now possible because of this change:
- Course names are loaded as soon as saved courses are fetched, and the loading indicator is displayed while it fetches the sections for each course
- It's now impossible (at least as far as I can tell) to overwrite your saved courses, since it checks if any course cards are loading before trying to save, and there should always be a course card loading from the time the page loads until either the fetch for saved courses fails, or all of the cards have been loaded.
I also added error handling to several places in the courseCards redux and course card column, I think that now it's robust enough that it shouldn't throw errors regardless of what any …
=> Optimize course card loading

autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.css, autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.tsx, autoscheduler/frontend/src/components/SchedulingPage/Schedule/InstructionsDialog/InstructionsDialog.css, autoscheduler/frontend/src/components/SchedulingPage/Schedule/InstructionsDialog/InstructionsDialog.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/Schedule/InstructionsDialog/InstructionsDialog.tsx, autoscheduler/frontend/src/components/SchedulingPage/Schedule/Schedule.tsx
The instructions for how to create availabilities would never be read by users if they stayed in the `ConfigureCard`, where they were before this PR. This PR moves the instructions into a dialog that obscures the schedule until the user dismisses it.
The new, schedule-covering dialog is set to appear by default, and can be removed if the user has saved schedules, if the user has generated schedules, or if the user presses OK. However, it might be worth considering setting a cookie so that it's only shown once per user, because I could easily see this becoming a nuisance if you don't have any saved availabilities.
Placed in a separate component because the `Schedule` component is already a little thicc.
Look at it: http://localhost:8080
If it's a frontend change, provide screenshots of it. …
=> Moved availability instructions to dialog

autoscheduler/frontend/src/components/App/App.css.d.ts, autoscheduler/frontend/src/components/GenericCard/GenericCard.css.d.ts, autoscheduler/frontend/src/components/LandingPage/LandingPage.css.d.ts, autoscheduler/frontend/src/components/LandingPage/SelectTerm/SelectTerm.css.d.ts, autoscheduler/frontend/src/components/LargeTextCard/LargeTextCard.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/CollapsedCourseCard/CollapsedCourseCard.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicSelect.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/GradeDist/GradeDist.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/Schedule/AvailabilityCard/AvailabilityCard.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/Schedule/HoveredTime/HoveredTime.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/Schedule/InstructionsDialog/InstructionsDialog.css, autoscheduler/frontend/src/components/SchedulingPage/Schedule/InstructionsDialog/InstructionsDialog.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/Schedule/Schedule.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/Schedule/ScheduleCard/ScheduleCard.css, autoscheduler/frontend/src/components/SchedulingPage/Schedule/ScheduleCard/ScheduleCard.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/Schedule/ScheduleCard/ScheduleCard.tsx, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleListItem/MiniSchedule/MiniSchedule.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/SchedulingPage.css.d.ts, autoscheduler/frontend/src/components/UnknownRoutePage/UnknownRoutePage.css.d.ts
Fix Z index for dialog and availability card
I also had to update the CSS `.d.ts` files built by our CSS loader, most likely due to an updating the package back in #351 
To test dialog, clear local storage. Reload. Add JAPN 201 for term Fall 2020. Include Full sections. Generate. Availability instructions dialog should cover classes.
To test availability cards, generate any schedule. Hover over meeting time in schedule. Move cursor to the start time label. Click and begin dragging. Stop dragging at end time label. Availability should be covering classes the entire time.
=> Fix Z index for dialog and availability card

.github/workflows/backend-workflow.yml, autoscheduler/autoscheduler/settings/docker.py, autoscheduler/scraper/management/commands/scrape_courses.py, autoscheduler/scraper/management/commands/utils/scraper_utils.py, autoscheduler/scraper/tests/commands/scraper_utils_tests.py, docker-compose.yml, docker/scrape-courses/Dockerfile, docker/scrape-courses/entrypoint.sh, entrypoint.sh
So this is mainly two parts: getting scrape_courses to connect to Google Cloud SQL and running scrape courses in Docker, and adding `--recent` flag to `scrape_courses`. I'll also discuss how the scheduling works in GCP, but since it's all just configs you really can't see the changes in this PR lol.
So this actually won't work if you run it locally since the cloud sql proxy won't be authenticated. However if you run it on Compute Engine, it uses Google Default App Credentials that are automatically on the Compute Engine instance, so we don't need to pass any credentials.
Since I added new docker containers to the `docker-compose.yml` file, so we run the according container by specifying it, e.g. `docker-compose up --build scrape-courses` (`cloud-sql-proxy` will automatically start since …
=> GCP: Scrape courses on a schedule

autoscheduler/frontend/src/components/LargeTextCard/LargeTextCard.tsx
Fixes the `validateDOMNesting` error that was occurring due to a `<div>` being nested under a `<p>`. I fixed this by changing the `Typography` component from `<p>` (default) to a `<div>`
Pretty straightforward - just build + run the website and check that it doesn't throw an error on the landing page. Can also look at the tests for `App.tsx` to show that the error doesn't occur.
Screenshots showing that no change has occurred for the cards that use `LargeTextCard`
|Before|After|
|--|--|
|![chrome_sYDjUH00yp](https://user-images.githubusercontent.com/7295783/95122043-8f035500-0715-11eb-9dad-75a083ce7bfc.png)|![chrome_g4Vn3JC6Gn](https://user-images.githubusercontent.com/7295783/95122060-93c80900-0715-11eb-9dda-e2ec890cc295.png)|
|![chrome_hrpigJcE86](https://user-images.githubusercontent.co …
=> Fix validateDOMNesting error

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.tsx
Makes it so empty course cards no longer get saved
I tried making a test for this for literally an hour and a half and then gave up, why do you have to do this to me jest? Good news is this PR is literally half a line so it should be pretty straightforward to see how it works
Try saving your course cards when you have all empty/a mix of empty and filled cards, it will only keep the ones with courses. ez
Closes #325.
=> Course cards without a course are no longer saved

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicSelect.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicSelect.tsx, autoscheduler/frontend/src/tests/ui/CourseSelectCard.test.tsx
Changed "there are no honors or online courses" to "sections" and added right padding.
Make sure "There are no honors or online sections for this class" shows up under "Customization Level" when "Basic" is selected.
Issue #356
=> Fixed text for no honors or web-based sections

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionInfo.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx, autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/tests/ui/SectionSelect.test.tsx
Spam-clicking a section in `SectionSelect` currently results in a really uncomfortable lag period where the UI is frozen. I originally attempted to fix this by virtualizing the list, but virtualization results ina an uncomfortable lag period where the `SectionSelect` is blank. I have found a better solution in memoization, which is basically the functional component equivalent of `shouldComponentUpdate`. Specifically, I moved the display for each section out of `SectionSelect` and into a new component called `SectionSelect`. Next, I memo-ized this `SectionInfo`, instructing it not to re-render unless it has been selected/de-selected. Significantly, this makes the assumption that none of the other fields or sub-fields in `SectionSelected` will ever change without also completely …
=> Memoized SectionInfo component

autoscheduler/scraper/models/section.py, autoscheduler/scraper/serializers.py, autoscheduler/scraper/views.py
Prefetches instructors and meetings in `/api/sections`, which solves the [N+1 selects problem](https://stackoverflow.com/questions/97197/what-is-the-n1-selects-problem-in-orm-object-relational-mapping) that made us use far more queries than necessary to fetch section data.
I also reorganized some parts of the section serializer to be easier to read (rename `obj` to `section`, ternary for instructor name), and added `related_name='meetings'` to meetings so that we can get meetings for a section with `section.meetings`.
Note that getting grades still takes a query for each section, I couldn't figure out a way to optimize it since `instructor_performance` performs a query and with the way that serializers work in DRF, the only way to stop this is with caching (which should be done in a …
=> Database access optimization for /api/sections

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionInfo.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx, autoscheduler/frontend/src/types/Meeting.ts
Adding a tooltip to the meeting type under "section select".
Hover over a meeting type and make sure that the abbreviation matches the tooltip
Closes #298
https://app.zenhub.com/workspaces/rr-5f735a6a098ca70016574cf1/issues/aggie-coding-club/rev-registration/298
=> Instruction type tooltips

autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/redux/reducers/courseCards.ts
Fixes the bug described in #412.
This can still technically happen if you delete the auto-generated card before `get_last_term` completes:
since the term changes, causing the card you deleted to be recreated after the term changes. The only way around this would be to not recreate the initial card when `clearCourseCards` is dispatched, but I think this way is probably better since that's a bit weird and it's hard to replicate this unless you're trying to do it on purpose.
Try to replicate this bug on master/production and see how easy it is, then try it on this branch. No tests made because there's no determinate way to replicate it (as it has to do with how async actions are ordered)
Closes #412.
=> Fixed bug where cards deleted when loading are recreated

autoscheduler/frontend/templates/index.html
As discussed in the last meeting, we'll be adding Google Analytics to the site so we can track hitcounts and the like.
Note that if you have an adblocker (uBlock origin, etc) it'll block this script.
I've invited everyone to the Google analytics account, which you can view at http://analytics.google.com, but here's what the homepage looks like:
Per this addition, I made a task (#408) for adding a privacy policy page.
=> Add Google Analytics script

autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.tsx, autoscheduler/frontend/src/hooks/useThunkDispatch.ts, autoscheduler/frontend/src/redux/actions/schedules.ts, autoscheduler/frontend/src/tests/ui/ConfigureCard.test.tsx, autoscheduler/frontend/src/tests/ui/SchedulingPage.test.tsx
Multi day availabilities were very laggy, so I did some profiling and realized that the ConfigureCard was being re-rendered very frequently. This occurred because the ConfigureCard needed access to the most up-to-date availabilities list, which was constantly being updated. By extracting the `generateSchedules` functionality to a Thunk Action, I can simply request the most up-to-date availabilities list once, at the time of schedule fetching, rather than asking for it constantly via `useSelector`.
I got rid of the "no schedules generated snackbar" because it would be a hassle to pass information back from Redux to the UI, and we can deal with that problem later, since we have to replace the snakcbar with a dialog anyway.
Automated tests are note possible for this bug, as it deals with …
=> Thunkified generateSchedules

autoscheduler/requirements.txt
For some reason, GCP keeps failing b/c asyncio is listed as a requirement, but it's built into Python since 3.4 (I think) so there's no need for it to be a requirement.
=> Removed asyncio from requirements

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.tsx
Uses `className` instead of CSS rules to dynamically change CSS
I noticed that using `className` instead of modifying CSS rules directly achieves the same thing and is a lot cleaner, so I changed it to do that instead
Basically just check the behavior in the different cases for card sizes/remaining space, this seems to have the same effect
=> Cleaned up code to change expanded row CSS

.github/workflows/deploy-workflow.yml
Now that we're close to launch, we don't want GCP to deploy immediately on pushes to `master`. This makes it so that GCP only deploys on pushes to the branch `production`, which I also made a protected branch (like `master` was already). This way we have to make a PR to actually deploy to GCP.
=> Made GCP only deploy on pushes to production

autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.tsx, autoscheduler/frontend/src/tests/ui/SchedulingPage.test.tsx
Makes the no schedules text seem less like an error and instead direct users to generate schedules.
I thought this wording was good because it directs users to the button and tells them that schedules will be generated using their course cards. Could change classes to course though, idk
use ur eyes and look at the screen
If you're changing a existing frontend look, provide a before and after screenshot in the table below.
|Before|After|
|--|--|
| ![image](https://user-images.githubusercontent.com/28655462/97505268-9a2d5780-1946-11eb-8772-0822c1d71dec.png) | ![image](https://user-images.githubusercontent.com/28655462/97505254-939ee000-1946-11eb-8850-6e5dc0e85cf4.png) | …
=> Made text when no schedules have been created more helpful

autoscheduler/frontend/src/components/SchedulingPage/Schedule/AvailabilityCard/AvailabilityCard.css, autoscheduler/frontend/src/components/SchedulingPage/Schedule/AvailabilityCard/AvailabilityCard.tsx, autoscheduler/frontend/src/components/SchedulingPage/Schedule/Schedule.tsx, autoscheduler/frontend/src/components/SchedulingPage/Schedule/ScheduleCard/ScheduleCard.css, autoscheduler/frontend/src/components/SchedulingPage/Schedule/ScheduleCard/ScheduleCard.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/Schedule/ScheduleCard/ScheduleCard.tsx
Hides time cursor when hovering over availability. Primarily important because it makes the trash icon visible so you can properly delete availabilities. May also consider turning the whole availability into a delete button, but I feel that is a little unexpected.
No tests because a) it's crunch time, and b) I'ma keep it real with you, this is 100% testable but I hate tests
Create an availability. Move your cursor over it. Note that it doesn't hide them when you're dragging a different availability.
No issue made for this one
=> Hides time cursor when hovering over availability

autoscheduler/frontend/src/components/NavBar/LoginButton.tsx, autoscheduler/frontend/src/tests/ui/NavBar.test.tsx
Redirects you back to your current page when logging in
We had said we wanted this functionality but didn't know how to do it, so I decided to implement it after seeing the solution looking up an unrelated problem
Try logging in from the homepage, scheduling page, some 404 page, etc.
n/a
=> Keep route on login

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionInfo.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx
Makes instructors sticky to make long lists more comprehensible and adds inset dividers below each section to make the space feel more organized.
In order to make all instructor subheaders the same height, I set the minimum height to 20px. This is because the instructor subheaders stack on top of each other when they are sticky, so if one is bigger than the others, it will stick out. There is a possibility that 20px will not work on other screens, but I doubt it since the honors icon (which is the determining factor) should always be the same size.
Look at a course with multiple instructors and sections, like CSCE 121. No automated tests included, mainly because it's impossible. …
=> Mini dividers + make instructors sticky for Course Cards

autoscheduler/scheduler/create_schedules.py, autoscheduler/scheduler/tests/scheduling_tests.py
Previously, when selecting a full section in section select and generating a schedule when "include full sections" was not selected, the section manually selected in section select would not be included. This PR makes it so that all sections manually selected in section select can be included in schedules regardless of whether include full sections is selected or not
Select some courses and go to section select. Select full sections for that course. After you have selected the sections and courses, make sure "include full sections" is not selected on the configure card. Generate schedules. If the schedule generated includes the full sections you manually selected, it should be working. I also added one backend test.
Doesn't close anything but a temp quality of life improvement meanwhile …
=> Section select overrides include full sections

autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleListItem/MiniSchedule/MiniSchedule.css
Adds a border to the mini-schedule. Shoutout to @firejake308 for helping me undo the last-row weirdness of the schedule. Note that you'll have to change line 25 in `autoscheduler/scheduler/views.py` to `asynchronous = BasicFilter(course.get("asynchronous", BasicFilter.NO_PREFERENCE))` to make `/scheduler/generate` work.
It looks way better
Generate a schedule and look at the border
|Before|After|
|--|--|
|![chrome_mUuZYJ6jcE](https://user-images.githubusercontent.com/7295783/97621866-7a9f3900-19f1-11eb-86a5-f4f4e308fc4e.png)|![chrome_UrU5LGST0g](https://user-images.githubusercontent.com/7295783/97621871-7e32c000-19f1-11eb-89f3-304fa647c4ed.png)|
Closing tag. Don't forget to link the issue w/ the PR in ZenHub at the bottom.
Closes #416
=> Added border to mini-schedule

autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.css, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.tsx, autoscheduler/frontend/src/components/SchedulingPage/SchedulingPage.tsx, autoscheduler/frontend/src/redux/actions/schedules.ts, autoscheduler/frontend/src/redux/reducers/schedules.ts, autoscheduler/frontend/src/tests/testData.ts, autoscheduler/frontend/src/tests/ui/SchedulePreview.test.tsx, autoscheduler/frontend/src/tests/ui/SchedulingPage.test.tsx, autoscheduler/frontend/src/types/APIRequests.ts, autoscheduler/scheduler/views.py, autoscheduler/scraper/serializers.py, autoscheduler/user_sessions/tests/schedules_api_tests.py, autoscheduler/user_sessions/urls.py, autoscheduler/user_sessions/views.py
Adds saving schedules to the session. Note that this is based off of #410 due to its addition of the abstract get/set state route functionality.
I set the throttle time 5 seconds since I don't expect schedules to be modified much, but we can increase it if we really want to.
Generate schedules then save (and rename) them, refresh the page, and ensure the schedules were saved.
Closes #267
=> Save schedules

autoscheduler/frontend/src/components/App/App.css, autoscheduler/frontend/src/components/App/App.css.d.ts, autoscheduler/frontend/src/components/App/App.tsx
Makes the full height of the page apply correctly on macOS Safari. Tbh only like 6% of our users use macOS Safari (36.51% use Safari, but only 15% of those are macOS) but still it's unusable without this.
Just build it and make sure it doesn't regress anything on y'all's end
Landing page
|Before|After|
|--|--|
|<img width="1680" alt="Screen Shot 2020-11-10 at 8 34 53 PM" src="https://user-images.githubusercontent.com/7295783/98759328-7b8f7d80-2396-11eb-937f-5748139beaaf.png">|<img width="1680" alt="Screen Shot 2020-11-10 at 8 35 00 PM" src="https://user-images.githubusercontent.com/7295783/98759358-8cd88a00-2396-11eb-9114-6fa14cb3b784.png">|
Schedule page
|Before|After|
|--|--|
|<img width="1680" alt="Screen Shot 2020-11-10 at 8 35 17 PM" …
=> Made height apply correctly on macOS Safari

autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleListItem/MiniSchedule/MiniSchedule.css, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleListItem/MiniSchedule/MiniSchedule.tsx
There was a weird 1-px margin at the top of the mini schedules, and when I went to fix that, I realized that the times didn't quite match up for classes later in the day. Consequently, I also included the fix to that bug as well.
Removing the random 1px margin should help make the border look better. Also, tbh, I no longer remember what its original purpose was. And fixing the bug is good because it makes the mini schedules more accurate, although tbf, users probably wouldn't look hard enough to notice.
Generate a schedule. Zoom in on the mini schedule. Look if there is any space between the maroon headera and the 8:00 bar. Then, count out the hours to a class in the middle of the day. Make sure it matches what you see in the big schedule.
The dark green class is KINE 199-242, which …
=> Fixed mini schedule sizing problems

autoscheduler/frontend/src/components/LandingPage/SelectTerm/SelectTerm.tsx, autoscheduler/frontend/src/tests/ui/SelectTerm.test.tsx
Caches the result of `api/terms`, meaning it will only ever be called once
I used a self-executing function to store state instead of doing it in global scope to make the caching self-contained
Also the test doesn't technically assert that `api/terms` is only called once for a couple reasons:
- `fetchMock` isn't actually adding the api call to the results of `fetchMock.mock.calls` for some reason
- The test will fail if it's called twice anyways, since the component won't know how to handle the response
What I was doing instead of checking out the navbar term select branch is just add multiple `<TermSelect />` components to the main page, you'll notice the call only executes once …
=> Cache terms api

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicSelect.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicSelect.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicSelect.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/InstructionalMethodIcon/InstructionalMethodIcon.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/InstructionalMethodIcon/InstructionalMethodIcon.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/InstructionalMethodIcon/InstructionalMethodIcon.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionInfo.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx, autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/redux/testData.ts, autoscheduler/frontend/src/tests/redux/CourseCards.test.ts, autoscheduler/frontend/src/tests/redux/Redux.test.ts, autoscheduler/frontend/src/tests/redux/Schedule.test.ts, autoscheduler/frontend/src/tests/testData.ts, autoscheduler/frontend/src/tests/testSchedules.ts, autoscheduler/frontend/src/tests/types/Meeting.test.ts, autoscheduler/frontend/src/tests/ui/CourseSelectCard.test.tsx, autoscheduler/frontend/src/tests/ui/MeetingCard.test.tsx, autoscheduler/frontend/src/tests/ui/Schedule.test.tsx, autoscheduler/frontend/src/tests/ui/SchedulePreview.test.tsx, autoscheduler/frontend/src/tests/ui/SectionSelect.test.tsx, autoscheduler/frontend/src/theme.ts, autoscheduler/frontend/src/types/Section.ts
Adds icons for instructional methods.
We've discussed whether we like all the icons here so there shouldn't be anything too controversial in this PR
You can see most of the icons by looking at courses for MATH 151, ENGL 210, and JAPN 491, see `InstructionalMethodIcon.tsx` to look at all of them
If you're changing a existing frontend look, provide a before and after screenshot in the table below.
|Before|After|
|--|--|
| ![image](https://user-images.githubusercontent.com/28655462/101934352-1603fc00-3ba3-11eb-983e-d766577863e5.png) | ![image](https://user-images.githubusercontent.com/28655462/101934482-43e94080-3ba3-11eb-9cff-d11311ff7a0f.png) |
Closes #432.
=> Instructional method icons

autoscheduler/frontend/src/tests/redux/CourseCards.test.ts
Fixes the test from master that failed after merging the instructional method icon PR
A test was added to master that didn't have the correct parameters for a section leading to compilation failing
Run tests
n/a
=> Fix test failing after merge

autoscheduler/frontend/src/components/SchedulingPage/Schedule/MeetingCard/MeetingCard.css, autoscheduler/frontend/src/components/SchedulingPage/Schedule/MeetingCard/MeetingCard.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/Schedule/MeetingCard/MeetingCard.tsx, autoscheduler/frontend/src/components/SchedulingPage/Schedule/ScheduleCard/ScheduleCard.tsx, autoscheduler/frontend/src/tests/testData.ts, autoscheduler/frontend/src/tests/ui/ConfigureCard.test.tsx, autoscheduler/frontend/src/tests/ui/CourseSelectCard.test.tsx, autoscheduler/frontend/src/tests/ui/MeetingCard.test.tsx, autoscheduler/frontend/src/tests/ui/Schedule.test.tsx, autoscheduler/frontend/src/tests/ui/SchedulingPage.test.tsx
Fixes the bug where the meeting type was being shown regardless of card size.
Turns out the bug was caused by my setting one of the `ScheduleCard` div's to use `display: contents;` in #438. I still think we need that CSS rule, so instead I just adapated the JS that we use to determine the height of all of the text in the card and the height of the card available.
Add a small class to your schedule
On a side note, the color scheme for this is literally awful after seeing how it looks on #463 
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/10082177/99754919-1848ce00-2aaf-11eb-9359-c9bbef1f2c84.png)|![image](https://user-images.githubusercontent.com/10082177/99754836-e59ed580-2aae-11eb-912d-5158fa5f127b.png)|
Closes #458 
Makes it easier to implement instructional …
=> Meeting type is once again hidden if card is small

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.tsx, autoscheduler/frontend/src/components/SchedulingPage/Schedule/Schedule.tsx, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.tsx, autoscheduler/frontend/src/redux/actions/availability.ts, autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/redux/actions/schedules.ts, autoscheduler/frontend/src/redux/actions/termData.ts, autoscheduler/frontend/src/redux/reducers/availability.ts, autoscheduler/frontend/src/redux/reducers/courseCards.ts, autoscheduler/frontend/src/redux/reducers/schedules.ts, autoscheduler/frontend/src/redux/reducers/termData.ts, autoscheduler/frontend/src/tests/redux/Availability.test.ts, autoscheduler/frontend/src/tests/redux/CourseCards.test.ts, autoscheduler/frontend/src/tests/redux/Schedule.test.ts, autoscheduler/frontend/src/tests/ui/Schedule.test.tsx, autoscheduler/frontend/src/tests/ui/SchedulePreview.test.tsx, autoscheduler/frontend/src/types/CourseCardOptions.ts
> This PR is based off of #472, which is based on #349
In essence, this fixes all of the issues with term mismatches when switching terms that we discovered in #349, including:
- Course cards' `get_saved_courses` (filling in the course title + card info)
- Course cards' `api/sections` (filling in the sections for sessions)
- Saved schedules
- Availabilities
I would highly suggest going commit-by-commit with this, as I tried to make the commits self-contained in their changes.
Note that the commit `Made ADD_COURSE_CARD reject mismatched terms` (15c0d65) is what fixes the `get_saved_courses` issues from [Ryan's most recent comment](https://github.com/aggie-coding-club/Rev-Registration/pull/349#issuecomment-727628534) on #349.
I must have spent like 15 hours on term select at this point
So …
=> Fix term select after redux-rearrange

autoscheduler/frontend/src/components/SchedulingPage/Schedule/ScheduleCard/ScheduleCard.css
We currently have a CSS bug where the start/end times for a meeting can be covered by an adjacent meeting if there's not enough time between classes. It looks like we've tried to fix this before, because we already have a style rule that increases the `z-index` on hover, but it's not being applied due to the element style rule taking priority. I fixed this by adding `!important` to the `.schedule-card:hover` style rule.
I could have also considered changing the `zIndex` that is applied in JavaScript at line 82 of `ScheduleCard.tsx`, but `!important` felt less invasive and less likely to break other things.
Add PHYS 202-513 to your schedule. The recitation and lab times are back to back, so this should generate an overlap on GCP but you should be able to see the time on this branch. …
=> Times are no longer covered by adjacent meetings

autoscheduler/frontend/src/tests/types/Availability.test.ts, autoscheduler/frontend/src/tests/ui/Availability.test.tsx, autoscheduler/frontend/src/utils/timeUtil.ts
Extends FIRST_HOUR and LAST_HOUR for the schedule by 1 hour.
Classes such as KINE-199 have early times, so we have to account for them. Likewise, MATH classes frequently have exams that end at 10:30, so we need to account for it as well.
KINE 199-598 and MATH 151-521 for 202111 have early and late times. Likewise, CSCE 482 has 15 minute times
|Before|After|
|--|--|
|![chrome_Zk4h90oTTB](https://user-images.githubusercontent.com/7295783/107887080-6f94e980-6eb8-11eb-86b2-ac87563b5653.png)|![chrome_chRyg1wgfP](https://user-images.githubusercontent.com/7295783/107887085-74f23400-6eb8-11eb-8ce8-1a30cf6c74a4.png)|
Closes #370
=> Extended FIRST_HOUR and LAST_HOUR by 1 hour

.github/lint-requirements.txt, .github/workflows/backend-workflow.yml, autoscheduler/requirements.txt, autoscheduler/scraper/banner_requests.py, autoscheduler/scraper/tests/banner_requests_tests.py
I'm pretty sure the linting Action workflow we use, [GitHub Action for pylint](https://github.com/cclauss/GitHub-Action-for-pylint), upgraded it's pylint version, which is causing a few PR's to fail when you wouldn't expect them to (#511, #508, #494). This updates `pylint` (and `pylint_django`) to the most recent version, as well as fixes the linting errors that arose. As such, make sure to run `pip install -r requirements.txt` after this is merged so that you're up-to-date.
You'll need to fix your linting in VSCode by going to your `.vscode/settings.json` and adding the last line, `--django-settings-module=autoscheduler.settings.base` to your pylint arguments, which means it'll look like:
```json
"python.linting.pylintArgs": [
"--load-plugins",
"pylint_django", …
```
=> Fixed backend linting (on GitHub Actions)

autoscheduler/frontend/assets/webmanifest-cors-fix.json
This fixes the site.webmanifest CORS issue we were getting previously. Note that the file I'm adding doesn't actually do anything when it's in the repository - it's simply there for our memory.
To fix it, I did the steps Carlos gave in #436 - simply added the JSON and ran `gsutil cors set webmanifest-cors-fix.json gs://bucketname` (thank you @ThatJuanGuy !). This basically just tells Google Cloud Storage that if it's okay to share resources across origins (websites) if the origin is any of the URLs in `origin` in the JSON file.
Go on https://revregistration.com and check the console to make sure we're not getting a CORS error for `site.webmanifest` anymore.
Closes #436
=> Fix site.webmanifest CORS

.github/workflows/deploy-workflow.yml, autoscheduler/autoscheduler/settings/base.py, autoscheduler/user_sessions/tests/retrieve_data_session_tests.py, autoscheduler/user_sessions/utils/retrieve_data_session.py
Fixes the issue where users would end up with invalid sessions, leaving them stuck on the homepage for all of eternity
More concretely:
- Sessions now take 10 years to expire instead of 2 weeks, meaning no more users should run into the issue (unless they don't use the site for 10 years in which case we should probably delete their data anyways). 
- If a user ends up with an invalid `Session` object associated with their `UserToDataSession`, a new one will be created (to fix the sessions of users who have already encountered the issue)
This performs an additional query every time `retrieve_data_session` is called in order to check the `Session` is valid, as there's no way to determine this with 100% accuracy using only a `SessionStore` object: empty sessions are treated the same as ones …
=> User session fix

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicSelect.css, autoscheduler/frontend/src/components/SchedulingPage/Schedule/InstructionsDialog/InstructionsDialog.css
Firefox doesn't support `fit-content` which makes it so parts of the websites that use it look odd, for example:
This adds `-moz-fit-content` wherever `fit-content` is used to achieve the intended effect:
The basic options row is really wonky on firefox without this, and while the instructions dialog looks fine I figured I might as well change it so that it works the same across browsers.
Use firefox lol
See above
None, but I pointed out this issue during the last meeting
=> Use -moz- vendor prefix for fit-content

autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleListItem/ColorBox.tsx, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleListItem/ScheduleListItem.tsx, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.css, autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.css.d.ts
Replaces color boxes for sections with no meeting times with an X, and shows instructor names in the preview
I based this branch off of `schedule-details` because I reorganized the schedule preview significantly in that branch. No tests because I don't think they'd be very helpful but I could try to add some if we want.
I also resized `<ColorBox>` to be 1px bigger because the old size made it impossible to center the X, it would always be 1px off because of rounding
Mess around with adding async classes, also try resizing the window to see how the instructor names interact when cut off (they should truncate the text and add an ellipsis)
Before|After
--|--
Closes #491, #297.
=> Schedule preview improvements

autoscheduler/autoscheduler/settings/base.py, autoscheduler/frontend/src/.eslintrc.js, autoscheduler/frontend/src/components/NavBar/NavBar.tsx, autoscheduler/frontend/src/globals.ts, autoscheduler/frontend/src/index.tsx, autoscheduler/frontend/src/jest.config.js, autoscheduler/frontend/src/tsconfig.json, autoscheduler/frontend/src/webpack.config.js, autoscheduler/frontend/templates/index.html, autoscheduler/frontend/views.py
Uses minified production react when running on GCP, and doesn't give access to redux devtools when `npm run build` is run. I also improved the way globals work by letting our build tools know about their existence rather than having to manually import dummy variables to get around linter errors, since the old method only works if it uses a default export.
Using the new react versions in production should provide a significant speed boost (I've read ~2x-5x as fast from different sources— I'm surprised we hadn't really considered how much of a difference this might make), as well as saving ~150kB data transfer due to smaller file sizes. On the redux side I'm sure there are some small speed improvements since it doesn't need to add hooks to every dispatch.
You can test the behavior for GCP …
=> Use production react/redux in production

autoscheduler/frontend/src/components/LandingPage/SelectTerm/SelectTerm.tsx
Adds dropdown V icons to SelectTerm. Note for the LandingPage one, I added custom styles which pushes the icon to the far right of it.
Look at the landing page and make sure they look right on a variety of screen sizes.
|Before|After|
|--|--|
|![chrome_lwGRb2EAAl](https://user-images.githubusercontent.com/7295783/111913068-a915c300-8a29-11eb-929d-82123d94cfe8.png)|![chrome_Ha2yqzHpGp](https://user-images.githubusercontent.com/7295783/111913070-aca94a00-8a29-11eb-8019-11d4fa3bd99b.png)|
Closes #484
=> Added V dropdown icons to SelectTerm

.github/workflows/deploy-workflow.yml
Uses `Content-Encoding: gzip` for js files on cloud storage. This reduces the size of `main.js` from 2.55MB:
To 474KB:
website go fast = stonks
I deployed a version of this change based on `production` to the live site, you can visit it and check out that the file being served is compressed
Closes #440.
=> gzip main.js

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/ProfessorGroup.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionInfo.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css.d.ts, autoscheduler/frontend/src/tests/ui/SectionSelect.test.tsx
After merging with master, we discovered that the changes to CSS grid at the end reverted some of the desired behaviors from  earlier work. Specifically, if there is a single meeting for a section, its background should be white, not red, and the section number is clearly no longer aligned with the instructional method icon. These have both been fixed by this patch.
Should be simple enough, as it's 2 lines of CSS. Ask if you have questions though
Inspect visually in browser. See PSYC 107 for a class with 1-meeting sections and literally any class for the misalignes section number.
If you're changing a existing frontend look, provide a before and after screenshot in the table …
=> Fix instructor select bugs

autoscheduler/frontend/src/components/SchedulingPage/Schedule/Schedule.tsx, autoscheduler/frontend/src/tests/ui/Schedule.test.tsx, autoscheduler/frontend/src/utils/meetingsForSchedule.ts, autoscheduler/frontend/src/utils/meetingsForSection.ts
This adds the filtering/combining of duplicate meetings on the schedule
There's an example in Fall 2020, CSCE 121 - 597
|Before|After|
|--|--|
|![chrome_Mreqe0x3kn](https://user-images.githubusercontent.com/7295783/112761405-07a1ea80-8fb0-11eb-8245-5680802d6370.png)|![chrome_u3FPCoBBfw](https://user-images.githubusercontent.com/7295783/112761408-0d97cb80-8fb0-11eb-9f1b-b60a6e1f64b1.png)|
Closes #419
=> Filter duplicate meetings on schedule

.github/lint-requirements.txt
Locks pylint to `2.7.0` in `lint-requirements.txt`
Look at the checkmark
=> Fix actions backend linting

autoscheduler/frontend/src/components/LandingPage/LandingPage.tsx, autoscheduler/frontend/src/tests/ui/LandingPage.test.tsx
Re-adds the setting of null on the landing page that was accidentally removed in #515 so that the term in the navbar is reset to `Select Term`.
Also adds tests for it
Do the action I did in my gif
Closes #537
=> Set term to null on landing page

autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/tests/ui/CourseSelectColumn.test.tsx
Fixes the default sort direction (for the second course card, it works on the first one) and added sort direction to sessions.
Add two course cards (one new one) and double check they have the correct default sort direction. Change the sort direction to something else and ensure it saves it in the session
Closes #521
=> Fix default sort direction and add direction to sessions

autoscheduler/frontend/src/components/LandingPage/SelectTerm/SelectTerm.css
Makes the select term button on the landing page golden.
It's ugly but it attracts the user's attention, which will help compensate for the wall of text that is the landing page
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/10082177/116160815-52e71000-a6b8-11eb-90be-bc0c91c0c448.png)|![image](https://user-images.githubusercontent.com/10082177/116160784-4793e480-a6b8-11eb-91e9-317e17e30511.png)|
None
=> Made select term on landing page golden

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/GradeDist/GradeDist.tsx
Fixes the GradeDist scroll problem by removing arrows from tooltips.
Gannon wanted to see how this looked locally, we should be able to compare it to the current behavior and find out what we like best
| Deployment | This PR |
|--|--|
| ![image](https://user-images.githubusercontent.com/28655462/115162243-083a1800-a068-11eb-8808-3cd4471bc61b.png) | ![image](https://user-images.githubusercontent.com/28655462/115162287-459ea580-a068-11eb-896e-ac029a458e2f.png) |
(Note that instead adding `overflow-x: none` to the container looks identical to deployment but just doesn't add a horizontal scrollbar)
Closes #310.
=> Remove arrow from GradeDist tooltips

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/CourseSelectCard.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.tsx, autoscheduler/frontend/src/redux/actions/courseCards.ts, autoscheduler/frontend/src/redux/actions/schedules.ts, autoscheduler/frontend/src/tests/redux/Schedule.test.ts, autoscheduler/frontend/src/tests/ui/CourseSelectCard.test.tsx, autoscheduler/frontend/src/tests/ui/CourseSelectColumn.test.tsx, autoscheduler/frontend/src/theme.ts, autoscheduler/frontend/src/types/CourseCardOptions.ts
This adds a switch to the course card header which allows you to "disable" a course card, which includes or excludes it from the generated schedule. 
It also removes the `Collapse` and `Remove` text from the course card header in place of the "Include in schedule" text for the switch.
It also adds as custom switch since the default one was too tall and we didn't like the colors of it.
Add any 2 course cards, disable one of them, generate schedules, and ensure that the disabled course card isn't included in the generated schedule. 
Closes #379
=> Disable course cards

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.tsx
Setting the height in JavaScript is tricky because it means manually handling a lot of things that CSS usually manages. For cards larger than 500px, I had set the height to take up the maximum available space, but in reality, the height needs to be capped at the height of sectionRows
I originally missed this bug because my screen was too small, so make sure your screen is fairly large. Next, open a card that is larger than 500px but can fit within your screen. I used SPAN 301 atfer zooming out my screen to 50%. The card should take up only as much space as it needs, not the whole column.
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/10082177/116316011-f5fe5f00-a776-11eb-9745-201b894085f2.png)|![image](https://user-images.githubusercontent.com/10082177/116315867 …
=> Fixed bug where large cards take up extra space

autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.tsx, autoscheduler/scheduler/tests/api_tests.py, autoscheduler/scheduler/views.py
We've been getting an error from `/get_saved_schedules` which results from people having saved schedules with sections that are no longer available (since the previous Fall 2021 sections got nuked by the new ones). As such, this handles the situation by simply returning nothing when they're encountered. This will result in empty schedules which ofc isn't ideal, but at least they can recover from this (instead of being completely unable to use the schedule preview column)
To test the frontend handling:
~~Save a schedule (make sure `/get_saved_schedules` is called), then on line 67 in scheduler/views.py set `sections = ()` in the `sections_for_schedule` function to mimic it returning `None` for a section. Then refresh and ensure it shows an empty schedule (without the frontend change, it …
=> Fix unavailable section handling for /get_saved_schedules

autoscheduler/frontend/src/components/LandingPage/SelectTerm/NavBarSelectTerm.css, autoscheduler/frontend/src/components/LastUpdatedAt.tsx, autoscheduler/frontend/src/components/NavBar/LoginButton.tsx, autoscheduler/frontend/src/components/NavBar/NavBar.css, autoscheduler/frontend/src/components/NavBar/NavBar.css.d.ts, autoscheduler/frontend/src/components/NavBar/NavBar.tsx
Makes the navbar stay on one line rather than become thicc af
It starts looking a bit weird when the width goes below 600px (term select clips with name):
but this should be fixed with the mobile functionality PR and is incredibly unlikely on desktop so I don't think it's that big a deal
Describe the best way to test the specific changes you made. If it's covering a special case,
make sure to include the situations they should check out (i.e. PHYS 207 - 501, term 202031)
lol yikes
|Before|After|
|--|--|
| ![image](https://user-images.githubusercontent.com/28655462/115939132-bd067780-a462-11eb-8cc1-db9b6bf857a6.png) | ![image](https://user-images.githubusercontent.com/28655462/115939114-af50f200-a462-11eb-9c20-4ea25414673b.png) |
Closes #517.
=> One line navbar

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.tsx
Fixes a bug from #471 that Ryan reported. Closes #548 
I chose not to fix the lack of a transition when the user removes an expanded card. This is because the transition that plays by default feels off, in that the removed card disappears, the newly expanded card teleports up into its place, and then the new card expands with a transition. During #471, we decided that this was worse than not having any transition at all, which is what led me to disable this specific transition. Instead, when you remove a card, the new card magically pops into place (as it did before #471). I acknowledge that this is not the ideal, which would be to gradually collapse the card to be deleted while expanding the new card, then delete the old card. However, when I attempted to implement this, there was a lag …
=> Restored transtion after removing collapsed card

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/CourseSelectCard.tsx
Improves the functionality of the course select autocomplete in a couple ways:
- Clicking outside of the dropdown will no longer select the last hovered course
- No dropdown results no longer clears the text showing what course is selected (note that even before this PR it would keep the selected course, just not display it until the card is collapsed/expanded again)
We talked about these behaviors being undesired during the last meeting since they're unintuitive and annoying in most cases
Try replicating the gifs on this branch vs. deployment. Actual tests don't very worthwhile for this PR given it's just using default material UI behavior but can be added if someone thinks it's worth doing
|Before|After|
|--|--|
| ![1](https://user-images.githubusercontent.com/28655462/117584076-51621280 …
=> Improve course search behavior

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/GradeDist/GradeDist.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/ProfessorGroup.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx
Fixes #571 and #572
I fixed #571 by adding `zIndex` as a parameter of `<ProfessorGroup />`: due to [how stacking contexts work in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context), since each professor name header is a `sticky` element with identical z indices the tooltips will render under sequential headers.
There are only two ways to fix this:
- Remove tooltips from the flow of the page so that they can be placed in a stacking group with higher priority (e.g. use portal again)
- Give headers descending z indices so that the tooltips won't show below sequential headers
I opted for the second choice given we've determined we don't want to ơ̴̬̩̈́̆̿̓p̸̘̙̎̑͌ȩ̸̛̳̉̊͆ṅ̶̢̪̻̼̰̊̀͘͝ ̷͚̐̐̆̅͝t̸̗̪̥̘̹͑̈́h̷̛͙̭̐e̴̻͖̓̎̈́̓͝ …
=> GradeDist fixes

autoscheduler/frontend/src/components/LandingPage/SelectTerm/SelectTerm.css, autoscheduler/frontend/src/components/LandingPage/SelectTerm/SelectTerm.css.d.ts, autoscheduler/frontend/src/components/LandingPage/SelectTerm/SelectTerm.tsx, autoscheduler/frontend/src/tests/ui/SelectTerm.test.tsx
Adds a loading indicator to `<SelectTerm />` that shows up after loading for half a second
We said in the meeting last week that it would make the website seem unresponsive if the loading indicator showed up immediately, so I added a 500ms delay before starting to display the loading indicator: before that, the component displays as it did before.
Make the following change to make fetching terms take long enough to see the loading indicator locally:
Closes #375.
=> Term select loading indicator

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/GradeDist/GradeDist.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionInfo.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css.d.ts, autoscheduler/frontend/src/components/SchedulingPage/SchedulingPage.css, autoscheduler/frontend/src/components/SchedulingPage/SchedulingPage.tsx
Changes how space is distributed between the 3 columns on the SchedulingPage. Course cards will now always render on one line, with no wrapping. This is achieved by setting `min-width: 400px`. The remaining space is split in a 1:1:2 ratio between course column, the middle column, and the schedule, respectively. However, the middle column has a maximum width of 550px, after which point the remaining space is split between the course card column and the schedule in a 1:2 ratio. Neither the first nor the last column has a maximum width.
This PR also increases the `max-width` of grade distributions from `10rem` to `20rem`. 8px of margin have also been added between the instructor name and grade container in order to make this look good on small screens.
Earlier, we had discussed possibly …
=> Change calendar width

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/CourseSelectCard.tsx, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.css, autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.tsx, autoscheduler/frontend/src/tests/ui/SchedulingPage.test.tsx
This bug was originally discovered in #580, read the comments there for more context.
I elected to address both of the issues by adding 2px of padding-bottom to `.section-rows`, since we were going to do it anway in #523 
Bug 1 - Disable, then enable a course card repeatedly. The card should not grow. There is also a Jest test to ensure that this bug does not relapse.
Bug 2 - Open SPAN 301 in Chrome (not Firefox), and make sure your window is big enough to accommodate all sections without scrolling. If not, zoom out, then close and open the course card. There should be no scroll bar in the list of sections.
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/10082177/120127690-a6e88700-c185-11eb-8d88-7ed946c7ba90.png)|![image](https://user-images.githubusercontent.co …
=> Fixed bug with infinitely growing cards

autoscheduler/frontend/src/components/SchedulingPage/Schedule/MeetingCard/MeetingCard.tsx, autoscheduler/frontend/src/tests/ui/SchedulingPage.test.tsx
Fixes the bug described in #589.
Contrary to the issue description, this behavior has always existed as far as I can tell from checking out old commits so I couldn't just see when the behavior regressed and restore the old code. Due to needing the actual height of the meeting card component, it needs to render *something* before determining whether it has enough space, text will not be rendered until the card has rendered for the first time.
Open side-by-side with deployment and compare how one-line meeting cards look.
| Deployment | This PR |
|-|-|
|![dep](https://user-images.githubusercontent.com/28655462/122827653-3deabf80-d2aa-11eb-8547-523643c87670.gif) | ![me](https://user-images.githubusercontent.com/28655462/122827322-d16fc080-d2a9-11eb-91f6-d7240a754f60.gif) |
Closes #589.
=> Fix meeting card flash

autoscheduler/scraper/management/commands/scrape_courses.py, autoscheduler/scraper/management/commands/utils/scraper_utils.py, autoscheduler/scraper/tests/commands/scrape_courses_tests.py, autoscheduler/scraper/tests/commands/scraper_utils_tests.py
The initial plan was for this PR to just fix the `--year` parameter for `scrape_courses`, but trying to do so I noticed that terms were being saved that didn't have any courses. This made me realize we could simplify the logic by ignoring these extra terms instead of the band-aid fix of manually checking the terms to fix (which could break if TAMU hasn't posted classes for a term when we scrape, leading to a term that shows up but has no courses).
This could really be a 2-line PR if we just wanted to restore the previous behavior, but I think the simplification of our codebase and more robust term checking is worth the extra effort.
Try scraping the current year as well as next year, and notice that only terms with data are being saved. I added tests for terms without courses being saved …
=> Fix scrape courses --year parameter, check terms have data before saving

autoscheduler/frontend/src/components/SchedulingPage/SchedulingPage.css
Fixes the mobile view from screenshot schedules to position the screenshottable schedule from (0, 0) to (-WIDTH, -HEIGHT), which will ensure it's never going to appear "on" the screen.
I've tested it on my phone - you can test it by going to the debug console and changing the view to whatever and ensure it switches into the mobile view correctly
|Before|After|
|--|--|
|![chrome_KgBka8O70X](https://user-images.githubusercontent.com/7295783/140848318-3ec51326-d6ad-48b1-a213-7172542ee0f3.png)|![chrome_XH3nyRzpAj](https://user-images.githubusercontent.com/7295783/140848327-8b5379d2-f18b-43d3-85b9-6d81a717fb88.png)|
Closes #615
=> Fix mobile view from screenshot schedules changes

.github/workflows/deploy-workflow.yml, fill_discord_credentials.sh, fill_google_auth_credentials.sh
#601 didn't include adding the credentials during the deploy workflow, so this adds that.
I'm confident this is going to work so I'm just going to merge it - if it doesn't work it's an easy revert.
=> Fix feedback form deploy

autoscheduler/scraper/management/commands/scrape_grades.py
`scrape_grades` was failing with the error: `requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://web-as.tamu.edu/gradereport`
Seems like they updated the url from `/gradereport` to `/gradereports`. This changes it to that!
Run scrape grades locally, but I'm confident that this is going to work so I'm just going to merge it!
=> Fix scrape_grades route

gcp/cloud-function-update-scheduler.js
Adds the shifting of scrape schedules between once a day to once every 15 minutes, using cloud scheduler.
No need to focus on the code exactly (and note that putting this in the repo is more for future reference, as it's currently stored in a cloud function).
Go on console.cloud.google.com -> Cloud Scheduler and press "Run now" and ensure it updates the `scrape-courses-start-instance` frequency between once a day to once every 15 minutes.
Also ensure that the dates that are mentioned in the description reflect the frequencies.
Closes #541
=> Add automatic shifting of scrape courses schedule

autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleDetails/ScheduleDetails.tsx, autoscheduler/frontend/src/tests/testSchedules.ts, autoscheduler/frontend/src/tests/utilTests/hoursForSchedule.test.ts, autoscheduler/frontend/src/tests/utilTests/hoursForSection.test.ts, autoscheduler/frontend/src/utils/hoursForSchedule.ts, autoscheduler/frontend/src/utils/hoursForSection.ts
Adds a credit hour range like we discussed in #632 
Note that there's like ~3k sections that have `minCredits` == `maxCredits` for whatever reason, so I added case to check for it.
Could also change the dash to "to" if we'd prefer that
Test cases are pretty good IMO
If you're changing a existing frontend look, provide a before and after screenshot in the table below.
|Schedule Details|Main Schedule|
|--|--|
|![chrome_rXLiTbH39G](https://user-images.githubusercontent.com/7295783/160736272-7ff72ac0-8f4e-4197-b854-496f351bbc59.png)|![chrome_xwQxTbWX34](https://user-images.githubusercontent.com/7295783/160736285-e1336698-6973-41f4-90bf-de09d150b11d.png)|
Closes #632
=> Added credit hour range for Schedule Details + bottom schedule bar
