aggie-coding-club/Rev-Registration

autoscheduler/autoscheduler/settings.py
autoscheduler/autoscheduler/urls.py
autoscheduler/frontend/README.md
autoscheduler/frontend/apps.py
autoscheduler/frontend/src/App.tsx
autoscheduler/frontend/src/README.md
autoscheduler/frontend/src/index.tsx
autoscheduler/frontend/src/package-lock.json
autoscheduler/frontend/src/package.json
autoscheduler/frontend/src/tsconfig.json
autoscheduler/frontend/src/webpack.config.js
autoscheduler/frontend/templates/index.html
autoscheduler/frontend/tests.py
autoscheduler/frontend/urls.py
autoscheduler/frontend/views.py

Includes set up for:
- npm - our package manager
- webpack - compiles react & typescript into javascript for the browser to interpret
- typescript
- react
Closes #5

Implemented basic outline for frontend

---

autoscheduler/frontend/src/package.json
autoscheduler/frontend/src/redux/actionTypes.ts
autoscheduler/frontend/src/redux/actions.ts
autoscheduler/frontend/src/redux/reducers.ts
autoscheduler/frontend/src/redux/store.ts
autoscheduler/frontend/src/types.ts
autoscheduler/frontend/src/webpack.config.js

Closes #18 
Redux dependencies have been added to `package.json`, and the necessary files were created.

Setup Redux

---

autoscheduler/autoscheduler/settings.py
autoscheduler/scraper/models/__init__.py
autoscheduler/scraper/models/course.py
autoscheduler/scraper/models/department.py
autoscheduler/scraper/models/instructor.py
autoscheduler/scraper/models/section.py

**Take 3!**
Same thing as #26 and #27

Added scraper models outline

---

autoscheduler/scraper/models/department.py

Create Department Model

---

autoscheduler/scraper/models/instructor.py

Added instructor model. If we use the PIDM, I believe it should fit in IntegerField, name is really the only thing that's required, and email address is optional. Eventually, grade distributions will have to be stored somewhere, but I think that ought to be a separate table, since a professor might have a good grade distro for one class but not for another.
Closes #23

Instructor model

---

autoscheduler/scraper/models/course.py

Course model. Added some fields for core curriculum tags. Combined min/max credits into just credit hours. Left some comments as comments.
Closes #22 .

Implement Course model

---

.pylintrc
requirements.txt

Basically just wanna check that all of these sound right.
~~I also need to add a step to the README or wiki, as to get it working with `pylint-django` I believe you have to do `pylint --load-plugins pylint-django /path/to/folder/with/__init__.py/inside/`~~
The above is totally wrong. We may be able to provide it in the `load-plugins` thing in the rcfile, alternatively we can set VSCode pylint arguments

Setup pylint

---

autoscheduler/scraper/admin.py
autoscheduler/scraper/models/course.py
autoscheduler/scraper/models/department.py
autoscheduler/scraper/models/section.py
autoscheduler/scraper/tests/models_tests.py

- Adds term to Department and a composite primary key, plus a function for generating the id
- Adds a function to generate course id to Course file
- Fixes some formatting in Course & Section

Updated misc for Department, Course, Section models

---

.github/dangerfile.ts
.github/workflows/danger-workflow.yml

Added Danger.js

---

.github/dangerfile.ts
.github/workflows/backend-workflow.yml
.github/workflows/danger-workflow.yml
.github/workflows/frontend-workflow.yml

Includes Danger and splitting up GitHub actions into parts

Merge master into backend/master

---

.github/dangerfile.ts
.github/workflows/backend-workflow.yml
.github/workflows/danger-workflow.yml
.github/workflows/frontend-workflow.yml

Added Danger.js and splitting up actions into frontend/backend

Merge master into frontend/master

---

autoscheduler/frontend/urls.py

If the path doesn't match `/admin/`, then React-router will handle routing. This is going straight to master because it's backend code (in a `.py` file) that affects mostly the frontend

Let React handle routing

---

autoscheduler/scraper/management/commands/scrape_courses.py

Misc fixes for course scraping.
Mostly changes some nitpicky formatting stuff: renamed variables, elaborated on some doc strings & comments.
Also implements the changes that Ryan requested in his most recent review of #94.

Fixes for course scraping

---

README.md

Basically for the clout
Here's what they'll look like:

Added CI build badges to README

---

README.md

some general steps for setting up Postgres on Mac with brew and some debug steps for future reference

Added mac install instructions for main readme

---

.github/lint-requirements.txt
autoscheduler/autoscheduler/settings/base.py
autoscheduler/autoscheduler/urls.py
autoscheduler/scraper/models/section.py
autoscheduler/scraper/serializers.py
autoscheduler/scraper/tests/api_tests.py
autoscheduler/scraper/urls.py
autoscheduler/scraper/views.py

The tests are mostly complete, and done enough for backend to be able to start working on them so I'm going to merge it, see #125 & #115

Added scraper API tests

---

autoscheduler/scraper/models/__init__.py
autoscheduler/scraper/models/grades.py
autoscheduler/scraper/tests/models_tests.py

Adds the Grades model and GradeManager
After this is completed I'll do the actual `scrape_grades` command

Added Grades model for scrape_grades

---

autoscheduler/scraper/serializers.py
autoscheduler/scraper/tests/api_tests.py
autoscheduler/scraper/urls.py
autoscheduler/scraper/views.py

Implemented api section scraping. Added the appropriate lines in views.py and url.py. I tried to follow the function from where it would be called to when it would be pulling from the database and it seems good. Let me know if there's any other files I need to modify.
Closes #136

Implemented api/sections scraper route

---

autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectColumn.css

Using CSS flex to solve all of our problems

Fixed add course button getting cut off

---

autoscheduler/scraper/serializers.py
autoscheduler/scraper/tests/api_tests.py
autoscheduler/scraper/urls.py
autoscheduler/scraper/views.py

Implements api/grades and some tests for it

Implemented api/grades route

---

autoscheduler/frontend/src/components/App/testMeetings.ts
autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx
autoscheduler/frontend/src/components/Schedule/Schedule.tsx
autoscheduler/frontend/src/redux/testData.ts

Meeting days should start with Monday

---

autoscheduler/frontend/src/components/App/App.tsx
autoscheduler/frontend/src/components/App/Test.tsx
autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectCard/CollapsedCourseCard/CollapsedCourseCard.css
autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectCard/CollapsedCourseCard/CollapsedCourseCard.tsx
autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.css
autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.tsx

* Fixed font of header buttons
* Clicking anywhere on the header now expands/collapses
* changed remove icon to trash can for consistency

Course Select Card Improvements

---

autoscheduler/frontend/src/redux/actions/schedules.ts
autoscheduler/frontend/src/redux/actions/selectedSchedule.ts
autoscheduler/frontend/src/redux/reducer.ts
autoscheduler/frontend/src/redux/reducers/availabilityMode.ts
autoscheduler/frontend/src/redux/reducers/schedules.ts
autoscheduler/frontend/src/redux/reducers/selectedSchedule.ts
autoscheduler/frontend/src/tests/ReduxSchedulingPage.test.ts
autoscheduler/frontend/src/tests/testSchedules.ts

This is a smaller PR that isolates the changes made to Redux in order to support the new SchedulingPage

Redux changes for SchedulingPage

---

autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.tsx
autoscheduler/frontend/src/package-lock.json
autoscheduler/frontend/src/package.json

I just made a new branch to fix the incorrect rebase from #201 
The fix required updating Material UI, so you'll have to rerun `npm install`. Also, be on the lookout for any breaking changes. One minor bug I've noticed is that the autocomplete menu is sometimes misplaced for some reason, but it seems to be fixed when there are 2 course cards.
TODO automatically select if the user types the exact course
Closes #172

Fix redundant course search take 2

---

autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectColumn.css
autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectColumn.css.d.ts
autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectColumn.tsx
autoscheduler/frontend/src/tests/CourseSelectColumn.test.tsx

A lot of our users were confused by the positioning of our Add Course button. This PR puts the Add course button right below the last course card, but makes the button "sticky" so that it can't go below the bottom of the CourseSelectColumn. Make sure that the spacing looks right to y'all

Made Add Course button sticky

---

.github/workflows/deploy-workflow.yml

Corrected deploy-workflow syntax

---

autoscheduler/frontend/src/components/NavBar.tsx
autoscheduler/frontend/templates/index.html

- Changes the NavBar title and window title to "Rev Registration"
- Makes the NavBar title clickable and redirect to the landing page / root upon click
Probably should've made the branch `frontend/title-fixes`, but w/e

Frontend title fixes

---

autoscheduler/scraper/management/commands/scrape_grades.py

Once this is merged, I'll make a PR for #215 that implements multiprocessing for this
Closes #197

Changed scrape_grades to bulk query Sections

---

autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.tsx
autoscheduler/frontend/src/tests/ui/SchedulePreview.test.tsx

This adds the calculating of the average GPA from the given sections in a schedule to the schedules in `SchedulePreview`.
Closes #235

Display average GPA for schedules in SchedulePreview

---

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicOptionRow.tsx
autoscheduler/frontend/src/package-lock.json
autoscheduler/frontend/src/package.json
autoscheduler/frontend/src/tests/ui/BasicSelect.test.tsx
autoscheduler/frontend/src/tests/ui/CourseSelectCard.test.tsx

Quick bugfix cuz I forgot to update something when I created the BasicOptionRow component

Fixed bug where changing web would update honors instead

---

autoscheduler/frontend/src/components/SchedulingPage/Schedule/Schedule.tsx
autoscheduler/frontend/src/tests/ui/Availability.test.tsx

Added a test to replicate and a null-check to fix. Closes #268

Fixed bug when dragging outside of schedule component

---

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/ExpandedCourseCard.tsx

course cards now work with variable amounts of spaces.

course cards now work with variable amounts of spaces

---

autoscheduler/frontend/src/components/LandingPage/HelpText/HelpText.tsx

Updates the guidelines!
Note that the css I have here is temporary, but if we commit to using it I'll probs change it to be it's own file
|With `<br />'s`|With `<p>`'s (current)|
|--|--|
|![chrome_9wf9tKAfuo](https://user-images.githubusercontent.com/7295783/93029461-946ef300-f5e0-11ea-8372-deee873d8f70.png)|![chrome_PBE9wTd1ip](https://user-images.githubusercontent.com/7295783/93029463-96d14d00-f5e0-11ea-9839-f8c7ff62c8d0.png)|
Closes #334

Updated guidelines

---

.github/workflows/deploy-workflow.yml
autoscheduler/app.yaml

Makes app engine requests to the `http` version of the website redirection to `https`
I tried finding a way to do this with google domains, but you can't use DNS records to both provide redirection and use app engine to serve pages, so this seems like the only way to do it
I made it deploy a version of the site that redirects (will make sure the workflow change gets reverted) so we can test it out before merging into master
sexy
Closing tag. Don't forget to link the issue w/ the PR in ZenHub at the bottom.
Closes #335.

Add SSL redirection

---

autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleListItem/ScheduleListItem.tsx
autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.css
autoscheduler/frontend/src/tests/ui/SchedulePreview.test.tsx

Removed average GPA from schedule preview section.
Make sure that average GPA doesn't show up under each schedule
Closes #328

Remove Average GPA

---

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicOptionRow.tsx
autoscheduler/frontend/src/redux/actions/courseCards.ts
autoscheduler/frontend/src/redux/reducers/courseCards.ts
autoscheduler/frontend/src/tests/redux/CourseCards.test.ts
autoscheduler/frontend/src/tests/redux/Redux.test.ts
autoscheduler/scheduler/utils.py

Changed web default to no preference

---

autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.css
autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.css.d.ts
autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectColumn.tsx

TODO
If necessary, defend any changes that you made.
TODO
If you're changing a existing frontend look, provide a before and after screenshot in the table below.
|Before|After|
|--|--|
|Before Screenshot|After Screenshot|
Closing tag. Don't forget to link the issue w/ the PR in ZenHub at the bottom.
Closes #1

Added dynamic CSS rules to expanded row

---

LICENSE

Adds the license. I don't think we need to edit anything in this, but we might have to add a copyright notice in each file? Which I really don't want to do lol. Followed [these steps](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository) from GitHub docs.
Closes #428

Added GNU GPL v3 License

---

autoscheduler/user_sessions/tests/schedules_api_tests.py

Didn't merge master into this so didn't realize that the #444 would make one of the tests fail, so this fixes it

Fixed failing test

---

autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleListItem/MiniSchedule/MiniSchedule.css
autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleListItem/MiniSchedule/MiniSchedule.tsx

I'm gonna end up deploying to the site in a bit in #465 in a bit so figured we might as well

Merge master into production

---

autoscheduler/scraper/management/commands/utils/scraper_utils.py
autoscheduler/scraper/tests/commands/scraper_utils_tests.py

So it turns out that `get_all_terms` was working completely wrong (you can check by removing the changes I made and running the tests). This fixes it and adds tests for it.
Just check that the tests are running how you would expected

Term-select: Fixed get_all_terms
